version: '3.7'

services:
  drone-server:
    container_name: drone_server
    image: drone/drone:2
    ports:
      - 8080:80
    volumes:
      - /var/lib/drone:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - .drone_server_env
  
  drone-agent:
    container_name: drone_agent
    image: drone/agent:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - .drone_agent_env
