name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  PROD_HOST: $HOST
  PROD_USERNAME: $USERNAME

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secret.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ${{ secret.SSH_PRIVATE_KEY }} ${{ env.PROD_HOST }}@${{ env. PROD_USERNAME }} /bin/date
